name: Node Test

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE
    - name: Checkout Git Repository
      uses: actions/checkout@v2
    
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    # Runs a command using the runners shell
    - name: Install dependencies
      env:
          PIPENV_YES: "true"
      run: |
        npm install
        npm test